Fixed undefined option
Running the chrome manifest task fails with the following message:

    TypeError: Arguments to path.join must be strings
        at path.js:360:15
        at Array.filter (native)
        at Object.exports.join (path.js:358:36)
        at /Users/myusername/Sites/Addons/PS Ruler/node_modules/grunt-chrome-manifest/tasks/chrome-manifest.js:22:29
        at Array.forEach (native)
        at Object.<anonymous> (/Users/myusername/Sites/Addons/PS Ruler/node_modules/grunt-chrome-manifest/tasks/chrome-manifest.js:18:16)
        at Object.<anonymous> (/Users/myusername/Sites/Addons/PS Ruler/node_modules/grunt/lib/grunt/task.js:258:15)
        at Object.thisTask.fn (/Users/myusername/Sites/Addons/PS Ruler/node_modules/grunt/lib/grunt/task.js:78:16)
        at Object.<anonymous> (/Users/myusername/Sites/Addons/PS Ruler/node_modules/grunt/lib/util/task.js:282:30)
        at Task.runTaskFn (/Users/myusername/Sites/Addons/PS Ruler/node_modules/grunt/lib/util/task.js:235:24)

    Aborted due to warnings.